# ++++++++++ Small-scale configuration ++++++++++
CHANGE_LOCATION_INTERVAL = 15
CHANGE_REQUESTS_INTERVAL = 20
CHANGE_DYNAMICS_CYCLES = 10
NUMBER_OF_REQUESTS_MIN = 1
NUMBER_OF_REQUESTS_MAX = 10
REQUESTS_INTERVAL_MIN = 5000
REQUESTS_INTERVAL_MAX = 10000
MICROSERVICE_NODES_MIN = 10
MICROSERVICE_NODES_MAX = 20
NETWORK_NODES_MIN = 10
NETWORK_NODES_MAX = 20
LOG_FOLDER = "results/logs"
LOG_FILE = "app.log"
RAY_FOLDER = "results/ray"
YAFS_FOLDER = "results/yafs"
DATA_FOLDER = "data"

# ++++++++++ Medium-scale configuration ++++++++++
# CHANGE_LOCATION_INTERVAL = 10
# CHANGE_REQUESTS_INTERVAL = 15
# CHANGE_DYNAMICS_CYCLES = 10
# NUMBER_OF_REQUESTS_MIN = 5
# NUMBER_OF_REQUESTS_MAX = 50
# REQUESTS_INTERVAL_MIN = 2000
# REQUESTS_INTERVAL_MAX = 7000
# MICROSERVICE_NODES_MIN = 50
# MICROSERVICE_NODES_MAX = 100
# NETWORK_NODES_MIN = 50
# NETWORK_NODES_MAX = 100
# LOG_FOLDER = "results/logs"
# LOG_FILE = "app.log"
# RAY_FOLDER = "results/ray"
# YAFS_FOLDER = "results/yafs"
# DATA_FOLDER = "data"

# ++++++++++ Large-scale configuration ++++++++++
# CHANGE_LOCATION_INTERVAL = 5
# CHANGE_REQUESTS_INTERVAL = 10
# CHANGE_DYNAMICS_CYCLES = 10
# NUMBER_OF_REQUESTS_MIN = 20
# NUMBER_OF_REQUESTS_MAX = 100
# REQUESTS_INTERVAL_MIN = 500
# REQUESTS_INTERVAL_MAX = 3000
# MICROSERVICE_NODES_MIN = 100
# MICROSERVICE_NODES_MAX = 200
# NETWORK_NODES_MIN = 100
# NETWORK_NODES_MAX = 200
# LOG_FOLDER = "results/logs"
# LOG_FILE = "app.log"
# RAY_FOLDER = "results/ray"
# YAFS_FOLDER = "results/yafs"
# DATA_FOLDER = "data"
